raw_fasta_file: "/media/jcosme/Data/MarRef.training.fasta" # absolute path to location of raw .fasta file

clean_fasta_file: "/media/jcosme/Data/MarRef_parquet" # absolute path to output destination of parquet files (this will be a folder)

# add validation to make this a length = 2 list
# add validation to make sure these three variables make sense
base_col_names: ["seq", "label"]

fasta_sep: ">" # DO NOT TOUCH THIS