preblock_filters: 32
preblock_kernel_sizes: [7]
preblock_pool_size: 3
idblock_kernel_sizes: [5]
idblock_filters: [32, 64, 128]
idblock_activation: 'gelu'
idblock_avg_pool_sizes: [11]
last_activation: 'softmax'


batch_size: 4096
learn_rate: 0.0005
epochs: 300
patience: 299
num_warmup_epochs: 2
warmup_lr_multiplier: .001
from_logits: false

TF_MEMORY_ALLOCATION: '0.8'
TF_VISIBLE_DEVICE: '0'
TF_FORCE_GPU_ALLOW_GROWTH: 'true'

device_spill_frac: 0.15
protocol: 'tcp'
visible_devices: '0'
enable_tcp_over_ucx: false
enable_nvlink: false
enable_infiniband: false
rmm_pool_size: '1GB'

clear_models_dirs: true
clear_tensorboard: true
